@extends('website.layouts.app')
@section('title', 'Privacy Policy')
@section('style-css')   
<script src="https://unpkg.com/@phosphor-icons/web"></script>
  <link rel='stylesheet' id='popup-css-css' href="{{url('/website/css/magnific-popup.css')}}" media='all' />
  <link rel="stylesheet" href="{{url('/website/css/swiper-bundle.css')}}" />
  <link rel="stylesheet" href="{{url('/website/css/aos.css')}}">
  <link rel="stylesheet" href="{{url('/website/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.autoplay.css" />
  <link rel="stylesheet" href="{{url('/website/css/main.css')}}" />
  <link rel="stylesheet" href="{{url('/website/css/gallery.css')}}" />

  <!--form data submit common script-->
  <script src="{{url('/website/js/jquery.min.js')}}"></script>
@endsection
@section('style')   

@endsection
@section('content')
<div class="comm-section" data-aos="fade-in" data-duration="200">
      <div class="container">
        <div class="ftr-detail-wrap">
          <div class="container-tiny">
            <div class="ftr-content">
              <h2>Privacy Policy</h2>
              <h5><strong>Effective Date: February 11, 2025</strong></h5>
              <p>KG2PG Admissions is a duly incorporated company as per applicable laws in India having its Janardhan Towers, 2nd Floor, Residency Road, Above Indian Overseas Bank, Bengaluru, Karnataka, 560025 (hereinafter referred to as “we,” “us”, or “our”). We are engaged in the business of assisting students and parents for admissions in schools, colleges and universities of their choice, including in professional courses, in India and abroad ("Services"). This privacy policy ("Privacy Policy") explains how we collect, use and share information when you use our website and/or Services (hereinafter referred to as "Site"). We are committed to protecting your privacy and ensuring the security of your personal information.</p>
              <p>Any references to "you", "your" or "User" shall mean any person or entity using our Site. We will not use or share your information with anyone except as described in this Privacy Policy.</p>
              <p>Please note that by using the Site, you are consenting to the collection and use of your information by us. If you do not agree with the terms and conditions of this privacy policy, please do not use or access the Site. By mere use of the Site, you expressly consent to our collection and use of your personal information in accordance with this Privacy Policy. If you wish to withdraw consent, please refer to Clause 8 of this Privacy Policy.</p>
              <p>This Privacy Policy sets out the type of information collected from the Users, including the nature of the sensitive personal data or information, the purpose, means, and modes of usage of such information, and how and to whom we shall disclose such information, if any.</p>
              <h5><strong>Definitions</strong></h5>
              <p>For the purposes of this Privacy Policy, the capitalized terms shall have the meaning as ascribed to them hereinafter. Any capitalized terms not mentioned herein shall have the meaning as ascribed to them under the Terms.</p>
              <p>1.1 "Grievance Officer" means the grievance redressal officer appointed by us in accordance with Applicable Law, from time to time;</p>
              <p>1.2 "Personal Data" means data about a natural person, which can be used to identify such person. For the purposes of this Privacy Policy, “Personal Data” shall mean to include Sensitive Personal Data or Information;</p>
              <p>1.3 "Sensitive Personal Data or Information" shall have the same meaning as ascribed to it under Rule 3 of SPDI Rules;</p>
              <p>1.4 "Usage Data" shall mean data collected automatically- either generated by the use of the Site or from the Site infrastructure itself; and</p>
              <p>1.5 "User Information" shall mean to include any information relating to the user of the Site as may be collected from user's profile and activities while using the Site, including but not limited to Personal Data so collected, device information, location and network carrier.</p>
              <h5><strong>Information We Collect</strong></h5>
              <p>2.1 Personal Information: We collect Personal Data that is shared by you and stored within our system for availing our Services. This may include your Name, Phone number, guardian/parent’s name, educational qualifications and related details, and email address. The purpose of collecting this information is to provide our services and facilitate access to the database within the system.</p>
              <p>2.2 Usage Data: In order to gain insights into user interactions and enhance the functionality of our Site, we may collect various types of Usage Data. This includes but is not limited to, log files, IP addresses, device information, device location, and browsing activity. By gathering this information, we aim to gain a better understanding of how users engage with the Site, identify areas for improvement, and optimize its performance. The analysis of Usage Data allows us to enhance the user experience, tailor features to specific user preferences, and ensure the Site meets the evolving needs of our users. Please rest assured that the collection of this data is conducted in accordance with applicable privacy laws and regulations, and all necessary measures are taken to safeguard the confidentiality and security of the collected information.</p>
              <p>2.3 Information from other sources: We might receive information about you from other sources, such as any information uploaded by you on the Site, information from any personal correspondence received by us, etc.</p>
              <h5><strong>Use of Information</strong></h5>
              <p>We process your information for purposes based on legitimate business interests, the fulfilment of our contract with you, compliance with our legal obligations, and/or your consent. This information is based on your usage of the app or website. We process your Personal Data for these purposes in reliance on our legitimate business interests to provide our Services, in order to track your usage pattern (“Analytics”), and/or for compliance with our legal obligations (“Legal Purposes”). We indicate the specific processing grounds we rely on next to each purpose listed below.</p>
              <p>3.1 Providing Services: The Personal Data we collect is utilized to facilitate seamless Services and communication between you and us. This includes providing essential features such as call options and relevant information, enabling Users to efficiently connect and interact with each other. Additionally, we employ this Personal Data to maintain and track our Site. By utilizing personal information in this manner, we aim to streamline the user experience, foster productive business relationships with you, and enhance the overall functionality of the Site. We treat all Personal Data with the utmost care and in compliance with applicable privacy laws and regulations, taking appropriate measures to protect its confidentiality and security.</p>
              <p>3.2 Analytics: To continuously enhance the performance and functionality of our Site, we conduct a comprehensive analysis of usage data. This analysis serves multiple purposes, including improving the overall performance of the Site, enriching the quality of data, enhancing the user experience, and optimizing our Services and research purposes. By meticulously examining the usage data, we gain valuable insights into user behaviour, preferences, and patterns of interaction. These insights enable us to identify areas of improvement, refine features, and introduce enhancements that align with user needs and expectations. Additionally, the analysis of usage data allows us to optimize the performance of our Services, ensuring they are efficient, effective, and responsive to user requirements. Rest assured that during the analysis process, we strictly adhere to applicable privacy laws and regulations, safeguarding the confidentiality and anonymity of individual users while utilizing aggregated data to drive continuous improvements within the Site.</p>
              <p>3.3 Legal Purposes: We might use your data usage patterns and information collected from your usage to keep our Site safe and secure by involving technologies related to fraud monitoring and prevention. Apart from this, it may be used to protect our Site for business and/or for legal reasons if a legal request is placed on us.</p>
              <h5><strong>Use of Information</strong></h5>
              <p>We only share information with your consent, to comply with laws, to protect your rights, or to fulfill business obligations.</p>
              <p>4.1 With educational institutions and related parties: We share your Personal Data with schools and colleges of your choice, and related parties for the Services. This sharing of information is essential for our seamless operation and optimal Services to you. This sharing also helps to create an environment conducive to efficient and effective Site utilization, enabling smooth Services and enhancing user experiences.</p>
              <p>4.2 Our Partners & Business Obligations: As part of our commitment to continuous improvement and enhancing our services, we may share aggregated and anonymized usage data with our trusted partners for analytics and statistical purposes. It is important to note that in this process, any Personal Data associated with the aggregated data is carefully anonymized to ensure individual identities cannot be discerned. The purpose of sharing this data with our partners is to gain valuable insights into usage patterns, trends, and user behavior, allowing us to improve the functionality, features, and overall user experience of the Site. However, it is important to emphasize that your Personal Data is not shared with our partners for any other purposes, and all data is handled in compliance with applicable privacy laws and regulations. Our priority is to protect your privacy and maintain the confidentiality of your Personal Data while utilizing aggregated data to enhance the Site and provide a more valuable service to our users.</p>
              <p>4.3 Legal Requirements: We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal processes, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</p>
              <p>4.4 Business transfers: As we continue to develop our business, we might sell or buy other businesses or services. If we are involved in a merger, acquisition or asset sale, your Personal Data may be transferred. In such transactions, User information generally is one of the transferred business assets but remains subject to the Privacy Policy.</p>
              <h5><strong>Data Security</strong></h5>
              <p>We aim to protect your Personal Data through a system of organizational and technical security measures. We have implemented appropriate technical and organizational security measures designed to protect the security of any Personal Data we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your Personal Data, the transmission of Personal Data to and from our Sites is at your own risk. You should only access the services within a secure environment.</p>
              <h5><strong>Data Retention</strong></h5>
              <p>We keep your information for as long as necessary to fulfill the purposes outlined in this Privacy Policy unless otherwise required by law. We will only keep your Personal Data for as long as it is necessary for the purposes set out in this Privacy Policy unless a more extended retention period is required or permitted by law (such as tax, accounting or other legal requirements). No purpose in this policy will require us to keep your Personal Data for longer than 2 years.</p>
              <p>When we have no ongoing legitimate business need to process your Personal Data, we will either delete or anonymize it, or, if this is not possible (for example, because your personal data has been stored in backup archives), then we will securely store your Personal Data and isolate it from any further processing until deletion is possible.</p>
              <h5><strong>Your Rights</strong></h5>
              <p>In some regions, such as the European Economic Area, you have rights that allow you greater access to and control over your Personal Data. You may review, change, or terminate your account at any time. In some regions (like the European Economic Area), you have certain rights under applicable data protection laws. These may include the right (i) to request access and obtain a copy of your Personal Data, (ii) to request rectification or erasure; (iii) to restrict the processing of your Personal Data; and (iv) if applicable, to data portability. In certain circumstances, you may also have the right to object to the processing of your Personal Data. To make such a request, please use the contact details provided below in Clause 12. We will consider and act upon any request in accordance with applicable data protection laws. You have the right to withdraw your consent at any time. Please note however that this will not affect the lawfulness of the processing before its withdrawal. If you are a resident of the European Economic Area and you believe we are unlawfully processing your Personal Data, you also have the right to complain to your local data protection supervisory authority.</p>
              <h5><strong>Withdrawal of Consent Procedure</strong></h5>
              <p>You can opt out from collection or use of any Personal Data by our Site. To withdraw consent for collection and usage of Personal Data, please email unsubscribe to __________. It may take up to 7 (seven) days to process your request.</p>
              <p>We try to answer every request promptly wherever possible, and provide our response within the time period stated by applicable law. However, please keep in mind that when deleting your Personal Data there may be residual information that will remain within our databases, access logs, and other records, which may or may not contain your Personal Data. Please also note that certain Personal Data may be exempt from such requests in certain circumstances, which may include if we need to retain your Personal Data to comply with a legal obligation. When you email us with a request, we may ask that you provide us with information necessary to confirm your identity.</p>
              <h5><strong>Changes to the Privacy Policy</strong></h5>
              <p>We will update this policy as necessary to stay compliant with relevant laws. The updated version will be indicated by updating the “Effective Date” at the top of the Privacy Policy and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy policy, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this Privacy Policy frequently to be informed of how we are protecting your information.</p>
              <h5><strong>Linked Tools & Policies</strong></h5>
              <p>We may use third-party software for internal activities such as communication. There is no specific app that we have tagged within our system but given the common practices, Google Mail/Zoom is mostly used. Their terms of service and privacy policies can be referred to at their respective websites. Again, this is subjective to the app you engage with for different activities. If you click on one of the links to third party websites, you may be taken to websites we do not control. This Privacy Policy does not apply to the privacy practices of those websites. Read the privacy policy of other websites carefully. We are not responsible for these third-party sites.</p>
              <h5><strong>Children's Privacy</strong></h5>
              <p>We do not knowingly collect or solicit personal information from children under the age of 18 years and the Site and its content are not directed at children under the age of 18 years. In the event that we learn that we have collected personal information from a child under age 18 years without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 18 years. Please contact the Grievance Officer at the contact information set out in Clause 12 below.</p>
              <h5><strong>Contact Us</strong></h5>
              <p>If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact our Grievance Officer.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
@endsection
@section('scripts') 
<script>
      $(function() {
        $("#includeHtml").load("/common/floating_icon.html");
      });
    </script>   
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{{url('/website/js/lenis.min.js')}}"></script>
  <!-- aos JS -->
  <script src="{{url('/website/js/aos.js')}}"></script>
  <!-- Swiper Slider -->
  <script src="{{url('/website/js/swiper-bundle.min.js')}}"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.umd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.autoplay.umd.js"></script>

  <script src="{{url('/website/js/megamenu.js')}}"></script>
  <script src="{{url('/website/js/common.js')}}"></script>
  <script src="{{url('/website/js/about.js')}}"></script>
  <!--popup start-->
  <!-- <script src="{{url('/website/js/popup-form.js')}}" id="popup-form-js-js"></script> -->
  <!--popup form validation script-->

  <!--predictive script-->
  <link rel="stylesheet" href="{{url('/website/css/jquery-ui.css')}}">
  <script src="{{url('/website/js/jquery-ui.min.js')}}"></script>
  <script src="{{url('/website/js/predictive-course.js')}}"></script>
  <script src="{{url('/website/js/popupscript.js')}}"></script>

  <script>
    window.onload = function () {
      let intervalId = setInterval(function () {
        let badgeImage = document.querySelector('#iasBadge img');
        console.log("img: " + badgeImage);

        if (badgeImage) {
          badgeImage.style.width = '120px';
          badgeImage.style.height = '180px';


          var mq10 = window.matchMedia('(max-width: 1000px)');

          var mq5 = window.matchMedia('(max-width: 640px)');
          var mq4 = window.matchMedia('(max-width: 430px)');
          var mq3 = window.matchMedia('(max-width: 393px)');

          if (mq3.matches) {
            console.log(mq3);
                        // $('#iasBadge img').css({                            
                        //     'width': '40px',
                        //     'height': '65px'
                        // });
            $('#iasBadge img').css({
              'width': '150px',
              'height': '200px'
            });

          }

          else if (mq4.matches) {
            console.log(mq4);
            $('#iasBadge img').css({
              'width': '80px',
              'height': '100px'
            });
          }

          else if (mq5.matches) {
            console.log(mq5);
            $('#iasBadge img').css({
              'width': '110px',
              'height': '150px'
            });
          }
          else if (mq10.matches) {
            console.log(mq10);
            $('#iasBadge img').css({
              'width': '100px',
              'height': '110px'
            });
          }

                    // else {
                    //     $('#iasBadge img').css('');
                    // }

          clearInterval(intervalId);
        }
      }, 200);
    };
  </script>
@endsection